Update configure-azure-cni.md
MicrosoftDocs/azure-aks-docs pull request #52
Opened 2024-10-05 23:20 UTC by reknai

PR for https://supportability.visualstudio.com/AzureContainers/_workitems/edit/80451

2024-10-07 15:03 UTC, ShannonLeavitt commented
@reknai - Can you resolve the warnings listed above?

@asudbring - Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-10-08 17:48 UTC, schaffererin requested changes
Minor edits, but otherwise this is good for sign off!

2024-10-08 17:48 UTC, schaffererin commented on articles/aks/configure-azure-cni.md
> +  You can also [install Azure PowerShell locally](/powershell/azure/install-azure-powershell) to run the cmdlets. The steps in this article require Azure PowerShell module version 5.4.1 or later. Run
```suggestion
  You can also [install Azure PowerShell locally](/powershell/azure/install-azure-powershell) to run the cmdlets. The steps in this article require Azure PowerShell module version 5.4.1 or later. Run `Get-Module -ListAvailable Az` to find your installed version. If you need to upgrade for a specific OS, see [macOS][macOSUpgrade], [Windows][windowsUpgrade], or [Linux][linuxUpgrade].
```

2024-10-14 22:44 UTC, reknai commented
@ShannonLeavitt  Any update on the merging of this PR? Thx!

2024-10-14 23:42 UTC, asudbring commented
@reknai 
Please address the changes and feedback and then we can sign off for merge.
Thanks!

2024-10-15 16:50 UTC, reknai commented
@asudbring : the suggestions have been incorporated. Please check. Thank you!

2024-10-15 16:52 UTC, asudbring commented
> @asudbring : the suggestions have been incorporated. Please check. Thank you!

@reknai
I'm not seeing the changes or a new build happening.  You can commit the suggested changes in the comments and it will automatically commit them and rebuild the PR.  The last commit I'm seeing on this PR was 10/8.  If you made the changes locally you have to push them up to Github for this PR.

2024-10-15 17:13 UTC, reknai commented
@asudbring : I see it was not committed and I somehow missed it. Sorry about that. Now it should be in.

2024-10-15 17:17 UTC, asudbring commented
#sign-off

2024-10-15 21:43 UTC, merged