Update auto-upgrade-cluster.md
MicrosoftDocs/azure-aks-docs pull request #9
Opened 2024-08-03 07:39 UTC by azarboon

Hi. Following the advice from @Nickomang in [#122436](https://github.com/MicrosoftDocs/azure-docs/pull/122436), I've created this new PR which elaborates characteristics of auto upgrade:

""You don't need to stop your workloads, create a new AKS cluster or redeploy your workloads. By enabling auto-upgrade, you can ensure your clusters are up to date seamlessly and don't miss the latest features or patches from AKS and upstream Kubernetes. ""

Kindly please sign this off.

2024-08-05 15:29 UTC, Court72 commented
@Nickomang

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2024-09-04 21:25 UTC, schaffererin commented
#reassign:schaffererin

2024-09-04 21:29 UTC, schaffererin requested changes
Hi, @azarboon, thank you for your PR!

I suggested an edit that better aligns with the Microsoft writing style guidance. Once that suggestion is committed, this PR is good for sign off :)

2024-09-04 21:29 UTC, schaffererin commented on articles/aks/auto-upgrade-cluster.md
> +Cluster auto-upgrade provides a "set once and forget" mechanism that yields tangible time and operational cost benefits. You don't need to stop your workloads, create a new AKS cluster or redeploy yo
```suggestion
Cluster auto-upgrade provides a "set once and forget" mechanism that yields tangible time and operational cost benefits. You don't need to stop your workloads, redeploy your workloads, or create a new AKS cluster. By enabling auto-upgrade, you can ensure your clusters are up to date and don't miss the latest features or patches from AKS and upstream Kubernetes.
```

2024-09-05 05:49 UTC, azarboon commented
> Hi, @azarboon, thank you for your PR!
> 
> I suggested an edit that better aligns with the Microsoft writing style guidance. Once that suggestion is committed, this PR is good for sign off :)

Thank you. Committed your suggestion. Please sign it off.

2024-09-06 20:09 UTC, schaffererin commented
#sign-off

2024-09-06 20:10 UTC, schaffererin commented
@Court72, could you please assist me in getting this PR signed off on? :)

2024-09-06 20:10 UTC, merged